language: java
jdk:
- oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_8aaa1b26af5b_key -iv $encrypted_8aaa1b26af5b_iv
  -in subkey.gpg.enc -out subkey.gpg -d

script:
    mvn clean deploy -P ossrh --settings .mvn.xml